version: '3.8'

services:
  book_catalog:
    build: ./book_catalog
    ports:
      - "8001:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres_db

  inventory_management:
    build: ./inventory_management
    ports:
      - "8002:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: